// UTN - Lab4 - Vue/lab4-vue-zodiaco/src/App.vue
<template>
    <div>
        <Menu v-bind:datosArray="datosArray" />
        <router-view v-bind:datosArray="datosArray" />
    </div>
</template>

<script> //-----------------------------------------SCRIPT--------------------------------------------
import axios from 'axios';
import Menu from './components/Menu.vue'

export default{
    name:'App',

    components:{
        Menu
    },

    data() {
        return {
            datosArray: [],        
        };
    },

    methods: {
        async getData() {
            try {
                let dataJson = await axios.get( "http://localhost:8080/test/tb/zodiaco.json" );
                this.datosArray = dataJson.data;
                console.log(this.datosArray);
            } catch (error) {
                console.error('Error al obtener los datos: ' + error);
            }
        },
    },

    mounted() {
        this.getData();
    },

}
</script>

// UTN - Lab4 - React/lab4-final-react/src/App.js
import './App.css';
import { Fragment, useEffect, useState } from 'react';
import axios from 'axios';
import { BrowserRouter, Route, Switch } from 'react-router-dom';
import Menu from './components/Menu';
import Home from './components/Home';
import Detalle from './components/Detalle';

function App() {

  const [datos,setDatos] = useState([]);
  const [datosFiltrados,setFiltrar] = useState(datos);

  useEffect(() => {
    axios('http://localhost:3000/filesjson/listado_facturas.json')
    .then(response => {      
      console.log(response.data);

      setDatos(response.data);
      setFiltrar(response.data);

    }).catch(error => {
      console.log('Error al obtener los datos: ' + error);})
  }, []);

  const buscar = (dataInput) => {
    let value = dataInput.target.value.toString().toLowerCase();   
    let resultadoFiltrado = [];
    console.log(value);

    resultadoFiltrado = datos.filter( (arreglo) => {
      return arreglo.nroDocRec.toString().toLowerCase().search(value) !== -1;
    });
    setFiltrar(resultadoFiltrado);
  }

  return (
    <Fragment>
      <BrowserRouter>
        <Menu buscar={buscar}/>
        <Switch>
          <Route exact path="/"> <Home datos={datosFiltrados}/> </Route>
          <Route exact path="/detalle/:nroCmp"> <Detalle/> </Route>      
        </Switch>
      </BrowserRouter>
    </Fragment>
  );
}

export default App;
